### ISSUE TITLE
ability to run jest through "yarn run"

### ISSUE THREAD

**Issue by faassen** [yacut/tester-jest#2]
I was hoping to try tester-jest, but it assumes a "jest" command. In projects such as those created with ``create-react-app`` or ``nwb`` you don't have a "jest" command but instead you use something like "yarn run test". While there's a way to set the jest binary, that doesn't seem to be the right way to activate yarn for a local project.

**Comment by faassen** [comment]
I could use ``node_modules/.bin/jest`` but this is a relative directory to the project root, so that doesn't help me much.

To pass a command-line argument to a "yarn run" script appears to involve "yarn run jesttest -- --coverage", i.e. a ``--`` before the command line arguments that should be passed along.

**Comment by yacut** [comment]
Hi. Thank you for the issue.
I will build in a future release the option to configure it or the auto detect for 'react-scripts'.
As a workaround for now, you can set in tester-jest config: 'Path to jest binary' to `npm` or `yarn` and in args list should be set first `test --`. 
https://ibb.co/jWHUTv

**Comment by yacut** [comment]
The feature is available since v 0.2.2. Enjoy :)

**Comment by faassen** [comment]
Thanks so much!
