### ISSUE TITLE
Separate jest config setting

### ISSUE THREAD

**Issue by hvolschenk** [yacut/tester-jest#23]
Hiya,

This is a bit of a mix between a bug and a feature request.
I usually split my jest configuration out of `package.json` into a `jest.config.json` file (And then run jest through `jest --config=./jest.config.json`).

Is there a way I can point to my config file as opposed to `package.json` for running the tests?
Maybe through a setting, or through auto-discovery of said file.

**Comment by yacut** [comment]
Unfortunately I don't have time now. PR welcome 🙏

**Comment by yacut** [comment]
But you can use "additional args" setting for this. 
<img width="1315" alt="screen shot 2018-03-07 at 08 20 07" src="https://user-images.githubusercontent.com/4711633/37078647-63e61078-21e0-11e8-88d8-d2ad000b21ee.png">

**Comment by hvolschenk** [comment]
@yacut That seems like a perfect solution. Thanks a lot!
