### ISSUE TITLE
It does noes not work

### ISSUE THREAD

**Issue by jhm-ciberman** [yacut/tester-jest#5]
It simply does not work. 
I just installed the package and the dependency. 
This is my current folder setup and one of my Jest tests:
![Screenshot](https://cloud.githubusercontent.com/assets/7988351/25575565/022770ca-2e2f-11e7-8298-0275119fda7d.png)

If you need more info, let me know. I am realy interested in this package. :)

**Comment by yacut** [comment]
Hello.
I have two assumptions:
- the scope is not configured correctly and the tester does not start any test (in this case the tester console output is empty)
- the tester starts the test, but does not receive any results from the jest (in this case the tester console output shows the jest problem)

If none of this, then I suggest a little wait until the release 1.0.0 :)

**Comment by jhm-ciberman** [comment]
I have restarted my PC and atom and now when I open the project the spining cat gif shows in the bottom bar, and in the console, but it keeps "loading" forever. 

![image](https://cloud.githubusercontent.com/assets/7988351/25605388/ddce93a4-2ee0-11e7-99ff-0c3dc9ce7890.png)

My settings for tester-jest are the default settings:

![image](https://cloud.githubusercontent.com/assets/7988351/25605480/69fcb810-2ee1-11e7-9d71-ec029fb44b3a.png)

And in my config.cson (I never edited it by hand)
```cson
  tester:
    showOutputAfterTestRun: true
  "tester-jest": {}
```

**Comment by yacut** [comment]
Please try version 1.0.0.
If you still have the problem, please post the console error messages here.

**Comment by kogal** [comment]
Why is this one closed?
I have exactly the same problem with tester-jest 1.1.8:

>  when I open the project the spinning cat gif shows in the bottom bar, and in the console, but it keeps "loading" forever

There are no console error messages..

**Comment by ma-pe** [comment]
same for me (both 1.1.8 and 1.2.4)
