### ISSUE TITLE
🎁 Open dialog window for confirming snapshot rewriting

### ISSUE THREAD

**Issue by nodkz** [yacut/tester-jest#9]
Add ability for confirming changing snapshot. Eg via a dialog window.

This test
```js
    it('snapshot test', () => {
      expect({ a: 1, b: 2 }).toMatchSnapshot();
    });
```
provides such output

<img width="925" alt="screen shot 2017-05-16 at 18 53 17" src="https://cloud.githubusercontent.com/assets/1946920/26107017/b7d406d6-3a69-11e7-86d7-53f770b3d152.png">

**Comment by yacut** [comment]
I fixed the bug with CI environment and added the setting for it. But I'm not sure that the confirmation window for updating the snapshot is so necessary. 

- Firstly, it seems to me that the user should first see what is being updated and only then have the possibility to do it. 'Tester Result' view shows the snapshot changes and there you can set the `-u` parameter in 'additional args' to update the snapshot.
- Secondly, it is not so easy to implement it technically. The tester only starts the provider's test and collects the results, but should not include the specific logic of the providers.

But if you have better ideas, I'm always open to them.

**Comment by nodkz** [comment]
You are correct, that user should decide what to do: update snapshot OR fix a test.

`-u` param is not a convenient way for updating. You may forget to remove it and all snapshot will be rewritten automatically.

And you are right about keeping specific logic inside of provider. So why not to allow for provider open notification which asks: Do you want to update snapshots? Before giving some answer user can review diffs. Or may just close this notification.

**Comment by yacut** [comment]
The feature released in v1.1.0.

**Comment by nodkz** [comment]
Works like a charm 👌
Thank you very much!

**Comment by nodkz** [comment]
Ooops small bug detected: Do not open new dialog window while previous is active.

<img width="522" alt="screen shot 2017-05-19 at 18 53 58" src="https://cloud.githubusercontent.com/assets/1946920/26248583/c8f22be8-3cc4-11e7-9f59-b51ca2082e26.png">
